In [1]:
import pandas as pd
import numpy as np 
from pathlib import Path

In [2]:
acc_new = Path(r'D:\Users\UFPB\gabriel ayres\MST\table_utils\new_acc_new.csv')
bc_new = Path(r'D:\Users\UFPB\gabriel ayres\MST\table_utils\bc_after_exclude.csv')
pres_new = Path(r'D:\Users\UFPB\gabriel ayres\MST\table_utils\dummy_ehr_new.csv')

acc = pd.read_csv(acc_new)
bc = pd.read_csv(bc_new)
pres = pd.read_csv(pres_new)
pres['componentlevelassessment'].value_counts()

Benign [2]                                2418
Negative [1]                              2313
Suspicious [4]                             566
Known Biopsy-Proven Malignancy [6]         323
Probably Benign [3]                        321
Need Additional Imaging Evaluation [0]      47
Highly Suggestive of Malignancy [5]         27
Name: componentlevelassessment, dtype: int64

In [3]:
pres['label'] = pres['componentlevelassessment'].apply(lambda x: str(x).split('[')[0].strip())
#pres.to_csv('label_added_dummy_ehr_new.csv', index=False)

In [4]:
bc.head()

,birads2after_acc,Unnamed: 1,birads45after_acc,Unnamed: 3,birads6after_acc
0,20055459.0,NaN,51127450,NaN,46409654.0
1,17301854.0,NaN,89156606,NaN,47841747.0
2,42280793.0,NaN,55790482,NaN,55482868.0
3,15301678.0,NaN,20723228,NaN,61172058.0
4,81569669.0,NaN,14682825,NaN,NaN

In [5]:
bc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   birads2after_acc   53 non-null     float64
 1   Unnamed: 1         0 non-null      float64
 2   birads45after_acc  67 non-null     int64
 3   Unnamed: 3         0 non-null      float64
 4   birads6after_acc   4 non-null      float64
dtypes: float64(4), int64(1)
memory usage: 2.7 KB

In [6]:
datasplit_step3 = pd.read_csv(Path(r'D:\PENN-MRI\penn-preprocessed_cropped2\penn-preprocessed_datasplit.csv'))

In [7]:
datasplit_step3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11014 entries, 0 to 11013
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dummy_acc   11014 non-null  int64
 1   UID         11014 non-null  object
 2   side        11014 non-null  object
 3   laterality  1286 non-null   float64
 4   label       11014 non-null  object
 5   Malignant   11014 non-null  int64
 6   Fold        11014 non-null  int64
 7   Split       11014 non-null  object
dtypes: float64(1), int64(3), object(4)
memory usage: 688.5+ KB

In [11]:
datasplit_step3[(datasplit_step3['laterality'].notna()) & (datasplit_step3['Malignant'] == 1)].drop_duplicates(subset='UID', keep='first')

,dummy_acc,UID,side,laterality,label,Malignant,Fold,Split
275,73304581,73304581_left,left,2.0,Known Biopsy-Proven Malignancy,1,0,train
824,39970652,39970652_left,left,2.0,Known Biopsy-Proven Malignancy,1,0,train
989,77695990,77695990_left,left,2.0,Known Biopsy-Proven Malignancy,1,0,val
1020,56131168,56131168_left,left,2.0,Known Biopsy-Proven Malignancy,1,0,train
1275,71795691,71795691_left,left,2.0,Known Biopsy-Proven Malignancy,1,0,train
...,...,...,...,...,...,...,...,...
10984,23614155,23614155_right,right,1.0,Known Biopsy-Proven Malignancy,1,0,val
10987,60807569,60807569_right,right,2.0,Known Biopsy-Proven Malignancy,1,0,val
10994,36464505,36464505_right,right,1.0,Known Biopsy-Proven Malignancy,1,0,train
10996,22621045,22621045_right,right,1.0,Known Biopsy-Proven Malignancy,1,0,train
10998,17027895,17027895_right,right,2.0,Known Biopsy-Proven Malignancy,1,0,train

In [15]:
datasplit_step3 = datasplit_step3[(datasplit_step3['laterality'].isna()) & (datasplit_step3['Malignant'] == 1)]
datasplit_step3 = datasplit_step3.drop_duplicates()
datasplit_step3.head()

,dummy_acc,UID,side,laterality,label,Malignant,Fold,Split
9,37250661,37250661_left,left,NaN,Suspicious,1,0,val
14,51026787,51026787_left,left,NaN,Suspicious,1,0,test
51,53721564,53721564_left,left,NaN,Suspicious,1,0,train
64,35355817,35355817_left,left,NaN,Suspicious,1,0,train
100,65666346,65666346_left,left,NaN,Suspicious,1,0,val

In [16]:
datasplit_step3.to_csv('malignants_with_no_laterality.csv', index=False)